export const InitialState = {
  Id: 0,
  AccountId: 0,
  QuotationNumber: "",
  EnglishDate: "",
  NepaliDate: "",
  ExpiredEnglishDate: "",
  ExpiredNepaliDate: "",
  Message: "",
  MessageStatement: "",
  QuotationDetails: [
    {
      Id: 0,
      OrderManagementId: 0,
      ItemId: "",
      Qty: "",
      UnitType: "",
      TotalAmount: "",
      UnitPrice: 0,
      Discount: 0,
      TaxRate: "",
      UserName: "",
      FinancialYear: "",
      CompanyCode: 0,
      DepartmentId: 0,
      WarehouseId: 0,
      BranchId: 0,
    },
  ],
  FinancialYear: "",
  CompanyCode: 0,
  BranchCode: 0,
  DepartmentId: 0,
  WareHouseId: 0,
  BranchId: 0,
};
