export const InitialProductData = {
  Id: 0,
  Name: "",
  categoryId: 0,
  Barcode: "",
  Tag: "",
  UnitTypeBase: "",
  UnitDivided: 0,
  UnitType: "",
  DepartmentId: 0,
  WareHouseId: 0,
  BranchId: 0,
  IsProduct: false,
  IsService: false,
  IsMenuItem: false,
  BestSeller :false,
  FeaturedSeller:false,
  Description: "",
  MetaDescription: "",
  PhoteIdentity: null,
  IdentityFileName: null,
  IdentityFileType: null,
  ExciseDuty: 0,
  TaxRate: 13,
  CostPrice: 0,
  MarginRate: 0,
  MenuItemPortions: [
    {
      Id: 0,
      Name: "",
      MenuItemPortionId: 0,
      Multiplier: 0,
      Price: 0,
      Discount: 0,
      OpeningStockRate: 0,
      OpeningStock: 0,
      OpeningStockAmount: 0,
      StockLimit: 0,
      ItemCode: "",
      MenuItemPortionPriceRanges: [
        {
          Id: 0,
          PositionId: 0,
          QtyMin: 0,
          QtyMax: 0,
          Price: 0,
        },
      ],
    },
  ],
  MenuItemPhotos: null,
};
