export const InitialContraData = {
  Id: 0,
  AccountType: null,
  Name: "Contra",
  AccountTransactionType: "",
  AccountTransactionDocumentId: 0,
  AccountTransactionTypeId: 0,
  SourceAccountTypeId: 0,
  ref_invoice_number: "",
  IsReversed: false,
  Reversable: false,
  TargetAccountTypeId: 0,
  Description: "",
  Amount: "",
  DebitAmount: 0,
  CreditAmount: 0,
  drTotal: "",
  crTotal: "",
  IdentityFile: false,
  TicketReferences: [],
  InventoryReceiptDetails: null,
  PurchaseDetails: null,
  SalesOrderDetails: null,
  UserName: "",
  CompanyCode: 0,
  FinancialYear: "",
  Date: "",
  BranchId: 0,
  AccountTransactionValues: [
    {
      AccountId: 0,
      AccountTransactionDocumentId: 0,
      AccountTransactionId: 0,
      AccountTypeId: 0,
      CompanyCode: 0,
      Credit: 0,
      Date: "",
      Debit: 0,
      Description: "",
      Exchange: 0,
      FinancialYear: "",
      IS_Bill_Active: false,
      IS_Bill_Printed: false,
      Id: 0,
      NVDate: "",
      Name: "",
      NepaliMonth: "",
      Printed_Time: "",
      Real_Time: false,
      Sync_With_IRD: false,
      UserName: "",
      entityLists: "",
      ref_invoice_number: null,
      BranchId: 0,
      LedgetBalance: 0,
    },
  ],
};
