export const InitialState = {
  Claims: [],
  Logins: [],
  Roles: [
    {
      UserId: "",
      RoleId: "",
    },
  ],
  FullName: "",
  UserName: "",
  Password: "",
  FirstName: "",
  LastName: "",
  RoleName: "",
  Level: 0,
  Email: "",
  PhoneNumber: "",
  IsActive: false,
  ResetPassword: false,
  JoinDate: "",
  Token: "",
  EmailConfirmed: false,
  PasswordHash: "",
  SecurityStamp: "",
  PhoneNumberConfirmed: false,
  TwoFactorEnabled: false,
  LockoutEndDateUtc: "",
  LockoutEnabled: false,
  AccessFailedCount: 0,
  Id: "",
};
