export const InitialState = {
  Name: "",
  DefaultFilterType: "",
  WorkingRule: "",
  SortOrder: "",
  NatureofGroup: "",
  GroupSubLedger: false,
  DebitCreditBalanceReporting: false,
  UsedforCalculation: false,
  PurchaseInvoiceAllocation: false,
  ISBILLWISEON: false,
  ISCOSTCENTRESON: false,
  ISADDABLE: false,
  ISREVENUE: false,
  AFFECTSGROSSPROFIT: false,
  ISDEEMEDPOSITIVE: false,
  TRACKNEGATIVEBALANCES: false,
  ISCONDENSED: false,
  AFFECTSSTOCK: false,
  SORTPOSITION: false,
  UnderGroupLedger: "",
};
