export const InitialState = {
  BranchId: 0,
  DepartmentId: 0,
  Discount: 0,
  FinancialYear: "",
  Id: 0,
  IsSelected: false,
  IsVoid: false,
  ItemId: 0,
  ItemName: null,
  MRPPrice: 0,
  OrderDescription: null,
  OrderId: 0,
  OrderNumber: 0,
  Qty: 0,
  Tags: null,
  TaxRate: 0,
  TotalAmount: 0,
  UnitPrice: 0,
  UnitType: null,
  UserId: "",
  WarehouseId: 0,
};
